name: Docker Compose Build

on:
  push:
    branches:
      - main  # Chạy khi có sự thay đổi trên nhánh main
    paths:
      - '**/*.yml'   # Chạy khi thay đổi bất kỳ file .yml (docker-compose.yml) trong repo
      - '**/*.yaml'  # Chạy khi thay đổi bất kỳ file .yaml trong repo
      - '**/*.dockerfile'  # Nếu có Dockerfile, có thể thêm dòng này vào

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Bước 1: Lấy mã nguồn từ repo
      - name: Checkout code
        uses: actions/checkout@v2

      # Bước 2: Cài đặt Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Bước 3: Cài đặt Docker Compose
      - name: Set up Docker Compose
        run: |
          sudo curl -L https://github.com/docker/compose/releases/download/$(curl -s https://api.github.com/repos/docker/compose/releases/latest | jq -r .tag_name)/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      # Bước 4: Build Docker Compose
      - name: Build Docker Compose
        run: |
          docker-compose -f docker-compose.yml build

      # Bước 5: Tùy chọn, chạy các container (optional)
      - name: Run Docker Compose
        run: |
          docker-compose -f docker-compose.yml up -d
